# Generated by Django 6.0.4 on 2026-05-05 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('crm', models.JSONField(blank=True, null=True)),
                ('closing', models.JSONField(blank=True, null=True)),
                ('qualification', models.JSONField(blank=True, null=True)),
                ('quality_alerts', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='onboarding.onboardingform')),
            ],
        ),
    ]
