# Generated by Django 6.0.4 on 2026-05-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_generatedmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingform',
            name='tipo_venda',
            field=models.TextField(blank=True, default=''),
        ),
    ]
