# Generated by Django 6.0.4 on 2026-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_onboardingform_tipo_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingform',
            name='apresenta_preco',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='condicao_especial',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='objecoes_fecha',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='passagem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='tipo_reuniao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
