# Generated by Django 6.0.4 on 2026-05-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_alter_onboardingform_apresenta_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingform',
            name='modelo_venda',
            field=models.CharField(blank=True, choices=[('honorario', 'Honorário fixo'), ('exito', 'Êxito (% do resultado)'), ('entrada', 'Entrada + parcelas'), ('mensalidade', 'Mensalidade recorrente'), ('pacote', 'Pacote único'), ('hibrido', 'Híbrido (fixo + êxito)')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='plano_selecionado',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='onboardingform',
            name='tem_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
