# Generated by Django 6.0.4 on 2026-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_migrate_crm_to_funnels'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmaterial',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedmaterial',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
