# Generated by Django 6.0.4 on 2026-05-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_materialshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingform',
            name='pipedrive_deal_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
