# Generated by Django 6.0.4 on 2026-05-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_onboardingrule_onboardingruleack'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccountMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipedrive_user_id', models.IntegerField(unique=True)),
                ('google_email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecordingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
                ('meet_code', models.CharField(max_length=64)),
                ('owner_google_email', models.EmailField(max_length=254)),
                ('dest_folder_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('done', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('file_id', models.CharField(blank=True, default='', max_length=128)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='onboarding__status_f4aa9b_idx')],
            },
        ),
    ]
