# Generated by Django 6.0.4 on 2026-05-22 13:51

from django.db import migrations


SCHEDULE_NAME = 'reconcile_recordings'
SCHEDULE_FUNC = 'onboarding.tasks.reconcile_recordings'


def create_schedule(apps, schema_editor):
    Schedule = apps.get_model('django_q', 'Schedule')
    Schedule.objects.get_or_create(
        name=SCHEDULE_NAME,
        defaults={
            'func': SCHEDULE_FUNC,
            'schedule_type': 'I',  # Schedule.MINUTES
            'minutes': 5,
            'repeats': -1,
        },
    )


def remove_schedule(apps, schema_editor):
    Schedule = apps.get_model('django_q', 'Schedule')
    Schedule.objects.filter(name=SCHEDULE_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_googleaccountmap_recordingjob'),
        ('django_q', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_schedule, remove_schedule),
    ]
