# Generated by Django 6.0.4 on 2026-06-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0012_schedule_reconcile_recordings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingform',
            name='apresenta_preco',
        ),
        migrations.RemoveField(
            model_name='onboardingform',
            name='closer',
        ),
        migrations.RemoveField(
            model_name='onboardingform',
            name='condicao_especial',
        ),
        migrations.RemoveField(
            model_name='onboardingform',
            name='empresa_scripts',
        ),
        migrations.RemoveField(
            model_name='onboardingform',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='onboardingform',
            name='fech_especifico',
        ),
        migrations.RemoveField(
            model_name='onboardingform',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='onboardingform',
            name='objecoes_fecha',
        ),
        migrations.RemoveField(
            model_name='onboardingform',
            name='passagem',
        ),
        migrations.RemoveField(
            model_name='onboardingform',
            name='perfil_operador',
        ),
        migrations.RemoveField(
            model_name='onboardingform',
            name='sdr',
        ),
        migrations.RemoveField(
            model_name='onboardingform',
            name='tipo_reuniao',
        ),
    ]
