# Generated by Django 6.0.4 on 2026-06-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_remove_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingform',
            name='como_descobriu_outro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='onboardingform',
            name='decisivo_prospeccao_outro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='onboardingform',
            name='experiencia_reuniao_outro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='onboardingform',
            name='fonte_conteudo_outro',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='onboardingform',
            name='indicador_sucesso_outro',
            field=models.TextField(blank=True, default=''),
        ),
    ]
