# Generated by Django 6.0.4 on 2026-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0015_reconcile_ondemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmaterial',
            name='theme',
            field=models.CharField(default='warm', max_length=32),
        ),
    ]
