# Generated by Django 6.0.4 on 2026-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0016_generatedmaterial_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedmaterial',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
